[application]

# dioxus project name
name = "Freemail"

# default platfrom
# you can also use `dx serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Freemail"

[web.watcher]
reload_html = true
index_on_404 = true

watch_path = ["src", "public/assets"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["./assets/style.css", "./assets/inbox.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[application.plugins]

available = true

required = []

[bundler]
# Bundle identifier
identifier = ""

# Bundle publisher
publisher = ""

# Bundle icon
icon = ["icons/icon.png"]

# Bundle resources
resources = ["public/*"]

# Bundle copyright
copyright = ""

# Bundle category
category = "Utility"

# Bundle short description
short_description = "Take back your inbox with Freemail!"

# Bundle long description
long_description = """
Freemail - email the way it should have always been
"""
